// (part of) ManiaDrive - CQFD Corp
// http://maniadrive.raydium.org/
// See mania_drive.c

// You're not supposed to read this unless you've finished solo mode ;)
char credits_lines[][38]={
/*
max len for each line:
"*************************************"
*/
"",
"",
"",
"",
"M A N I A D R I V E - C R E D I T S",
"",
"",
"- PEOPLE -",
"",
"-Code-",
"Game Design & Programming : Xfennec",
"WebServices : Prospere",
"",
"-Graph-",
"2D : batcox, CaptNCock, Xfennec",
"3D : batcox, RyLe, whisky, Xfennec",
"",
"-Testing-",
"batcox, Flex, Finch, Mage, Neub",
"ouille, Prospere, remouk, RyLe,",
"Totoro, vicente, whisky, Xfennec,",
"yoltie",
"",
"",
"- SOUNDTRACK -",
"",
"'I got it bad' (1:48)",
"The Napoleon Blown Aparts",
"",
"'Mine tonite' (2:08)",
"Rocket City Riot",
"",
"'The Devil...' (4:15)",
"Black Moon",
"",
"'erase and rewind' (2:28)",
"Horstreich",
"",
"'Nowhere to go' (2:06)",
"The Napoleon Blown Aparts",
"",
"'MeMak Racer 1' (1:28)",
"Neub (aka Revision 1.1)",
"",
"'revenge of yesterday' (1:59)",
"Horstreich",
"",
"'Superstar Destroyer' (2:47)",
"Zen Ace Ten",
"",
"And the current track :",
"'Bienvenue au Mexique' (1:26)",
"Mage",
"",
"All tracks are distributed under",
"Creative Commons 2.0 license",
"",
"",
"- TOOLS -",
"",
"-Art & data-",
"Blender - http://www.blender.org/",
"The Gimp - http://www.gimp.org/",
"MPlayer - The Movie Player and",
"MEncoder - http://www.mplayerhq.hu/",
"",
"-Libraries-",
"3D Game Engine : Raydium",
"",
"Physics : ODE and RayODE interface",
"Sound : OpenAL, Vorbis and OGG",
"Scripting : PHP and RayPHP",
"Rendering : OpenGL & GLU thru Raydium",
"WebServices : NuSOAP with PHP",
"Python bindings : Swig",
"HTTP Webserver : based on nweb",
"Jpeg : IJG's libjpeg",
"Special thanks to PLIB's PW",
"for window management",
"",
"-Code-",
"GCC and all suitable tools",
"Dev-C++ and MinGW for win32 port",
"Midnight Commander for mcedit",
"Subversion version control system",
"",
"- MISC -",
"",
"Huge thanks to every contributor to",
"ManiaDrive and Raydium engine,",
"to our supporters, to GPL & CC for",
"allowing such projects,",
"and to Nadeo for Trackmania games !",
"",
"... and to you for playing :)",
"",
"It may interest you :",
"ManiaDrive is 2 000 line long",
"Track Editor is 1 200 line long",
"Raydium engine is 30 000 line long,",
"5 years of (almost) daily work,",
"2.2 GB of various data,",
"120 pages of API documentation",
"",
"A Raydium public release generates :",
"25 GB of bandwidth in ten days,",
"500 000 hits,",
"with 50 000 search engine hits.",
"...",
"",
"",
"",
"",
"See you online and",
"stay tuned for next versions ! :)",

"EOL"};

int credits_nlines(void)
{
static int n=0;

if(!n)
    {
    for(n=0;;n++)
        if(!strcmp(credits_lines[n],"EOL"))
            break;
    }
return n;
}
